import Head from 'next/head';

export default function Nav() {
  return (
    <nav>
      <Head>
        <title>Next Typescript Starter</title>
        <meta
          name="description"
          content="Generated by create next app and customized"
        />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </nav>
  );
}
